steps:
# Your custom steps here
- name: 'alpine/bash'
  args: ['-c', 'echo $_SERVICE_NAME']
- name: 'alpine/bash'
  args: ['-c', 'echo $COMMIT_SHA']
- name: 'alpine/bash'
  args: ['-c', 'echo $BUILD_ID']
- name: 'alpine/bash'
  args: ['-c', 'echo $TRGGIER_ID']
- name: 'gcr.io/k8s-skaffold/pack'
  args: ['pack', 'build', 'europe-west3-docker.pkg.dev/abstratium-vault/cloud-run-source-deploy/abstratium-vault/abstratium-vault:$COMMIT_SHA', '--builder=gcr.io/buildpacks/builder:v1', '--network=cloudbuild', '--path=.', '--env=GOOGLE_ENTRYPOINT', '--env=GOOGLE_FUNCTION_TARGET']
  # args: ['pack', 'build', '-t', 'gcr.io/$PROJECT_ID/[SERVICE-NAME]:$COMMIT_SHA', '.'] 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west3-docker.pkg.dev/abstratium-vault/cloud-run-source-deploy/abstratium-vault/abstratium-vault:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args: ['gcloud', 'run', 'services', 'update', 'abstratium-vault', '--platform=managed', '--image=europe-west3-docker.pkg.dev/abstratium-vault/cloud-run-source-deploy/abstratium-vault/abstratium-vault:$COMMIT_SHA', '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$TRIGGER_ID', '--region=europe-west3', '--quiet']

